# A GitHub Action that offers an easy way to automatically add labels 
# to opened PRs depending on their head and/or base branch. The branches
# can be specified directly or using patterns, such as feature/* or bugfix/*.
#
# To use the PR Branch Labeler, you can add a YAML-based workflow file, 
# e.g..github/workflows/pr-branch-labeler.yml
# https://github.com/marketplace/actions/pr-branch-labeler

name: "label-pull-request-branch"
on: [pull_request]

jobs:
  label_prs:
    runs-on: ubuntu-latest
    steps:
    - name: Label PRs
      if: github.event.action == 'opened' # Only run the action when the PR was first opened
      uses: ffittschen/pr-branch-labeler@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
